package visual;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A <em>teaching model</em> of an API for <strong>registering sales over an
 * unreliable connection</strong> — the point-of-sale / mobile-courier problem
 * where the network drops in the middle of a request and the client cannot tell
 * whether the sale was registered or not.
 *
 * <p>The model has two sides:
 * <ul>
 *   <li>a <em>client</em> (the POS device) with a durable local queue: every
 *       sale is written locally first, with an idempotency key the client
 *       generates <em>once</em>, before the first send;</li>
 *   <li>a <em>server</em> with an idempotency store keyed by that key: the first
 *       request for a key applies the sale and stores the response, every later
 *       request for the same key returns the stored response and applies
 *       nothing.</li>
 * </ul>
 *
 * <p>A request can fail in two places, and the model makes both explicit,
 * because they look identical to the client but are completely different on the
 * server:
 * <ul>
 *   <li>{@link #attemptRequestLost(String)} — the request never reached the
 *       server, so nothing happened there;</li>
 *   <li>{@link #attemptResponseLost(String)} — the server handled the request
 *       and the response was lost on the way back, so the sale <em>is</em>
 *       registered while the client still thinks it is not.</li>
 * </ul>
 * In both cases the client retries with the same key, and the idempotency store
 * is what keeps the money correct.
 *
 * <p>{@code DOUBLE_CHARGE_DETECTED} is a purely didactic signal: when a newly
 * applied key carries the same item and amount as an already-stored one, the
 * model points out that the business action was registered twice. A real server
 * cannot and must not deduplicate by payload — the event exists only to make the
 * "new key on every retry" mistake visible.
 *
 * <p>Every step emits a {@link Trace} event with a bilingual description so the
 * UI can replay the stream without re-running the code. The model is
 * intentionally dependency-free.
 */
public class VisualSaleRegistration {

    /** First retry delay; each further failure doubles it, up to the cap. */
    private static final int BASE_BACKOFF_MS = 200;
    /** Upper bound on the retry delay, so backoff never grows without limit. */
    private static final int MAX_BACKOFF_MS = 6400;

    private final String device;

    /** Client-side durable queue: every sale ever recorded on this device. */
    private final Map<String, Sale> ledger = new LinkedHashMap<>();

    /** Server-side idempotency store: key -> the stored response for that key. */
    private final Map<String, Record> server = new LinkedHashMap<>();

    private boolean online = true;
    private int serverTotal;
    private int appliedCount;
    private int duplicateCount;
    private int doubleChargeCount;

    /** The last send attempt (null before the first one and after a drain). */
    private Attempt attempt;

    public VisualSaleRegistration() {
        this("pos");
    }

    public VisualSaleRegistration(String device) {
        this.device = device;
        Trace.event("POS_CREATED",
                "Device '" + device + "' is online with an empty local queue and an empty "
                        + "idempotency store on the server",
                "Устройство '" + device + "' онлайн, локальная очередь пуста и хранилище "
                        + "идемпотентности на сервере пусто",
                List.of(), state());
    }

    /**
     * Records a sale in the client's durable local queue. The {@code saleId} is
     * the idempotency key and is generated by the CLIENT, once, before any
     * network call — that is what makes every later retry safe.
     */
    public void recordSale(String saleId, String item, int amount) {
        attempt = null;
        ledger.put(saleId, new Sale(saleId, item, amount));
        Trace.event("SALE_QUEUED",
                "Sale '" + saleId + "' (" + item + ", " + amount + ") is written to the local "
                        + "queue first — the client generated this idempotency key before sending",
                "Продажа '" + saleId + "' (" + item + ", " + amount + ") сначала записана в "
                        + "локальную очередь — клиент сгенерировал этот ключ идемпотентности до отправки",
                List.of("sale:" + saleId), state());
    }

    /** Drops the connection: new sales are still recorded, but nothing can be sent. */
    public void goOffline() {
        attempt = null;
        online = false;
        Trace.event("CONNECTION_LOST",
                "The connection is down — the till keeps selling and queues sales locally "
                        + "instead of failing",
                "Соединение пропало — касса продолжает продавать и складывает продажи "
                        + "в локальную очередь вместо отказа",
                List.of(), state());
    }

    /**
     * Restores the connection and drains the local queue: every still-pending
     * sale is sent with its original key, so a sale the server already has is
     * deduplicated instead of applied twice.
     */
    public void reconnect() {
        attempt = null;
        online = true;
        Trace.event("CONNECTION_RESTORED",
                "The connection is back — the client starts draining its local queue",
                "Соединение восстановлено — клиент начинает выгружать локальную очередь",
                List.of(), state());

        List<String> pending = new ArrayList<>();
        for (Sale sale : ledger.values()) {
            if (!sale.confirmed) {
                pending.add(sale.id);
            }
        }
        for (String id : pending) {
            attemptDelivered(id);
        }

        attempt = null;
        Trace.event("QUEUE_DRAINED",
                "Queue drained: " + pending.size() + " pending sale(s) synced, server total is "
                        + serverTotal,
                "Очередь выгружена: синхронизировано отложенных продаж — " + pending.size()
                        + ", итог на сервере " + serverTotal,
                List.of(), state());
    }

    /**
     * An attempt whose request never reached the server (connection dropped on
     * the way out). Nothing changed on the server; the sale stays pending and a
     * retry is scheduled after an exponentially growing backoff.
     */
    public void attemptRequestLost(String saleId) {
        Sale sale = beginAttempt(saleId, "request_lost");
        Trace.event("REQUEST_LOST",
                "Attempt " + sale.attempts + " for '" + saleId + "' never reached the server — "
                        + "nothing was registered; retry in " + sale.nextRetryMs + " ms",
                "Попытка " + sale.attempts + " для '" + saleId + "' не дошла до сервера — "
                        + "ничего не зарегистрировано; повтор через " + sale.nextRetryMs + " мс",
                List.of("sale:" + saleId), state());
    }

    /**
     * An attempt the server fully handled, whose response was lost on the way
     * back. The sale IS registered, but the client cannot know that — from its
     * side this is indistinguishable from {@link #attemptRequestLost(String)},
     * which is exactly why the retry must carry the same idempotency key.
     */
    public void attemptResponseLost(String saleId) {
        Sale sale = beginAttempt(saleId, "response_lost");
        handleOnServer(sale);
        Trace.event("RESPONSE_LOST",
                "The server handled attempt " + sale.attempts + " for '" + saleId
                        + "' but the response was lost — the client still sees it as pending "
                        + "and will retry with the SAME key",
                "Сервер обработал попытку " + sale.attempts + " для '" + saleId
                        + "', но ответ потерян — клиент всё ещё считает продажу неподтверждённой "
                        + "и повторит с ТЕМ ЖЕ ключом",
                List.of("sale:" + saleId, "record:" + saleId), state());
    }

    /**
     * A full round trip: the server handles the request and the client receives
     * the acknowledgement, so the sale becomes confirmed and leaves the retry
     * queue.
     *
     * @return {@code true} if the server applied the sale now, {@code false} if
     *         the key was already known and the stored response was replayed
     */
    public boolean attemptDelivered(String saleId) {
        Sale sale = beginAttempt(saleId, "delivered");
        boolean applied = handleOnServer(sale);
        sale.confirmed = true;
        sale.nextRetryMs = 0;
        Trace.event("ACK_RECEIVED",
                "The client got the response for '" + saleId + "' on attempt " + sale.attempts
                        + " — the sale is confirmed and leaves the local queue; server total is "
                        + serverTotal,
                "Клиент получил ответ по '" + saleId + "' на попытке " + sale.attempts
                        + " — продажа подтверждена и покидает локальную очередь; итог на сервере "
                        + serverTotal,
                List.of("sale:" + saleId, "record:" + saleId), state());
        return applied;
    }

    /** Registers an attempt against a queued sale and updates its backoff. */
    private Sale beginAttempt(String saleId, String outcome) {
        Sale sale = ledger.get(saleId);
        if (sale == null) {
            throw new IllegalStateException("sale '" + saleId + "' was never recorded locally");
        }
        sale.attempts++;
        sale.nextRetryMs = backoffFor(sale.attempts);
        attempt = new Attempt(saleId, sale.attempts, outcome);
        return sale;
    }

    /**
     * The server side of one request: deduplicate by the idempotency key, and
     * only for a new key apply the sale and store its response.
     *
     * @return {@code true} when the sale was applied by this request
     */
    private boolean handleOnServer(Sale sale) {
        Record stored = server.get(sale.id);
        if (stored != null) {
            duplicateCount++;
            Trace.event("DUPLICATE_IGNORED",
                    "Key '" + sale.id + "' is already in the idempotency store — the server "
                            + "applies nothing and replays the stored response (" + stored.response
                            + "); total stays " + serverTotal,
                    "Ключ '" + sale.id + "' уже есть в хранилище идемпотентности — сервер ничего "
                            + "не применяет и повторяет сохранённый ответ (" + stored.response
                            + "); итог остаётся " + serverTotal,
                    List.of("record:" + sale.id), state());
            return false;
        }

        String twin = twinOf(sale);
        server.put(sale.id, new Record(sale.id, sale.item, sale.amount, "201 created"));
        serverTotal += sale.amount;
        appliedCount++;
        Trace.event("SALE_APPLIED",
                "New key '" + sale.id + "': the server registers the sale (" + sale.item + ", "
                        + sale.amount + ") and stores its response — total is now " + serverTotal,
                "Новый ключ '" + sale.id + "': сервер регистрирует продажу (" + sale.item + ", "
                        + sale.amount + ") и сохраняет ответ — итог теперь " + serverTotal,
                List.of("sale:" + sale.id, "record:" + sale.id), state());

        if (twin != null) {
            doubleChargeCount++;
            Trace.event("DOUBLE_CHARGE_DETECTED",
                    "The same sale (" + sale.item + ", " + sale.amount + ") is now stored twice, "
                            + "under '" + twin + "' and '" + sale.id + "' — the retry brought a NEW "
                            + "key, so the server had no way to deduplicate it",
                    "Одна и та же продажа (" + sale.item + ", " + sale.amount + ") теперь "
                            + "сохранена дважды, под '" + twin + "' и '" + sale.id + "' — повтор "
                            + "пришёл с НОВЫМ ключом, поэтому сервер не смог его дедуплицировать",
                    List.of("record:" + twin, "record:" + sale.id), state());
        }
        return true;
    }

    /**
     * Didactic check only: finds an already-stored record with the same item and
     * amount. A real server must NOT deduplicate by payload — two customers may
     * legitimately buy the same coffee for the same price.
     */
    private String twinOf(Sale sale) {
        for (Record r : server.values()) {
            if (r.item.equals(sale.item) && r.amount == sale.amount) {
                return r.key;
            }
        }
        return null;
    }

    /** Exponential backoff: BASE, 2*BASE, 4*BASE, … capped at MAX. */
    private static int backoffFor(int attempts) {
        int delay = BASE_BACKOFF_MS;
        for (int i = 1; i < attempts && delay < MAX_BACKOFF_MS; i++) {
            delay = Math.min(MAX_BACKOFF_MS, delay * 2);
        }
        return delay;
    }

    /** Builds the JSON-serializable snapshot consumed by the visualizer. */
    private Object state() {
        Map<String, Object> s = new LinkedHashMap<>();
        s.put("device", device);
        s.put("online", online);

        List<Object> sales = new ArrayList<>();
        int pending = 0;
        for (Sale sale : ledger.values()) {
            if (!sale.confirmed) {
                pending++;
            }
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", sale.id);
            m.put("item", sale.item);
            m.put("amount", sale.amount);
            m.put("status", sale.confirmed ? "confirmed" : "pending");
            m.put("attempts", sale.attempts);
            m.put("nextRetryMs", sale.nextRetryMs);
            sales.add(m);
        }
        s.put("sales", sales);
        s.put("pendingCount", pending);

        List<Object> records = new ArrayList<>();
        for (Record r : server.values()) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("key", r.key);
            m.put("item", r.item);
            m.put("amount", r.amount);
            m.put("response", r.response);
            records.add(m);
        }
        s.put("server", records);

        s.put("serverTotal", serverTotal);
        s.put("appliedCount", appliedCount);
        s.put("duplicateCount", duplicateCount);
        s.put("doubleChargeCount", doubleChargeCount);

        if (attempt != null) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", attempt.id);
            m.put("number", attempt.number);
            m.put("outcome", attempt.outcome);
            s.put("attempt", m);
        }
        return s;
    }

    private static final class Sale {
        final String id;
        final String item;
        final int amount;
        int attempts;
        int nextRetryMs;
        boolean confirmed;

        Sale(String id, String item, int amount) {
            this.id = id;
            this.item = item;
            this.amount = amount;
        }
    }

    private static final class Record {
        final String key;
        final String item;
        final int amount;
        final String response;

        Record(String key, String item, int amount, String response) {
            this.key = key;
            this.item = item;
            this.amount = amount;
            this.response = response;
        }
    }

    private static final class Attempt {
        final String id;
        final int number;
        /** request_lost | response_lost | delivered */
        final String outcome;

        Attempt(String id, int number, String outcome) {
            this.id = id;
            this.number = number;
            this.outcome = outcome;
        }
    }
}
